// Generated by gencpp from file epos2/Current.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_CURRENT_H
#define EPOS2_MESSAGE_CURRENT_H

#include <ros/service_traits.h>


#include <epos2/CurrentRequest.h>
#include <epos2/CurrentResponse.h>


namespace epos2
{

struct Current
{

typedef CurrentRequest Request;
typedef CurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Current
} // namespace epos2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::epos2::Current > {
  static const char* value()
  {
    return "68a96870bd31b1576c888aa798fc5c02";
  }

  static const char* value(const ::epos2::Current&) { return value(); }
};

template<>
struct DataType< ::epos2::Current > {
  static const char* value()
  {
    return "epos2/Current";
  }

  static const char* value(const ::epos2::Current&) { return value(); }
};


// service_traits::MD5Sum< ::epos2::CurrentRequest> should match 
// service_traits::MD5Sum< ::epos2::Current > 
template<>
struct MD5Sum< ::epos2::CurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::epos2::Current >::value();
  }
  static const char* value(const ::epos2::CurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos2::CurrentRequest> should match 
// service_traits::DataType< ::epos2::Current > 
template<>
struct DataType< ::epos2::CurrentRequest>
{
  static const char* value()
  {
    return DataType< ::epos2::Current >::value();
  }
  static const char* value(const ::epos2::CurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::epos2::CurrentResponse> should match 
// service_traits::MD5Sum< ::epos2::Current > 
template<>
struct MD5Sum< ::epos2::CurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::epos2::Current >::value();
  }
  static const char* value(const ::epos2::CurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos2::CurrentResponse> should match 
// service_traits::DataType< ::epos2::Current > 
template<>
struct DataType< ::epos2::CurrentResponse>
{
  static const char* value()
  {
    return DataType< ::epos2::Current >::value();
  }
  static const char* value(const ::epos2::CurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EPOS2_MESSAGE_CURRENT_H
