// Generated by gencpp from file epos2/CurrentRequest.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_CURRENTREQUEST_H
#define EPOS2_MESSAGE_CURRENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2
{
template <class ContainerAllocator>
struct CurrentRequest_
{
  typedef CurrentRequest_<ContainerAllocator> Type;

  CurrentRequest_()
    : position(0)
    , torque(0)  {
    }
  CurrentRequest_(const ContainerAllocator& _alloc)
    : position(0)
    , torque(0)  {
  (void)_alloc;
    }



   typedef int32_t _position_type;
  _position_type position;

   typedef int16_t _torque_type;
  _torque_type torque;




  typedef boost::shared_ptr< ::epos2::CurrentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2::CurrentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentRequest_

typedef ::epos2::CurrentRequest_<std::allocator<void> > CurrentRequest;

typedef boost::shared_ptr< ::epos2::CurrentRequest > CurrentRequestPtr;
typedef boost::shared_ptr< ::epos2::CurrentRequest const> CurrentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2::CurrentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2::CurrentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2::CurrentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2::CurrentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::CurrentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::CurrentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::CurrentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::CurrentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2::CurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cb57acdbedfef217fb52a07505245b2";
  }

  static const char* value(const ::epos2::CurrentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cb57acdbedfef21ULL;
  static const uint64_t static_value2 = 0x7fb52a07505245b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2::CurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2/CurrentRequest";
  }

  static const char* value(const ::epos2::CurrentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2::CurrentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position\n\
int16 torque\n\
";
  }

  static const char* value(const ::epos2::CurrentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2::CurrentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2::CurrentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2::CurrentRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "torque: ";
    Printer<int16_t>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_MESSAGE_CURRENTREQUEST_H
