// Generated by gencpp from file epos2/CurrentResponse.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_CURRENTRESPONSE_H
#define EPOS2_MESSAGE_CURRENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2
{
template <class ContainerAllocator>
struct CurrentResponse_
{
  typedef CurrentResponse_<ContainerAllocator> Type;

  CurrentResponse_()
    : position_new(0)
    , reward(0.0)
    , done(false)
    , velocity(0.0)
    , current(0)  {
    }
  CurrentResponse_(const ContainerAllocator& _alloc)
    : position_new(0)
    , reward(0.0)
    , done(false)
    , velocity(0.0)
    , current(0)  {
  (void)_alloc;
    }



   typedef int32_t _position_new_type;
  _position_new_type position_new;

   typedef double _reward_type;
  _reward_type reward;

   typedef uint8_t _done_type;
  _done_type done;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef int16_t _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::epos2::CurrentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2::CurrentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentResponse_

typedef ::epos2::CurrentResponse_<std::allocator<void> > CurrentResponse;

typedef boost::shared_ptr< ::epos2::CurrentResponse > CurrentResponsePtr;
typedef boost::shared_ptr< ::epos2::CurrentResponse const> CurrentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2::CurrentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2::CurrentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2::CurrentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2::CurrentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::CurrentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::CurrentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::CurrentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::CurrentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2::CurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f507fb6d316909e52211821daf76ac3a";
  }

  static const char* value(const ::epos2::CurrentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf507fb6d316909e5ULL;
  static const uint64_t static_value2 = 0x2211821daf76ac3aULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2::CurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2/CurrentResponse";
  }

  static const char* value(const ::epos2::CurrentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2::CurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position_new\n\
float64 reward\n\
bool done\n\
float64 velocity\n\
int16 current\n\
\n\
";
  }

  static const char* value(const ::epos2::CurrentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2::CurrentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_new);
      stream.next(m.reward);
      stream.next(m.done);
      stream.next(m.velocity);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2::CurrentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2::CurrentResponse_<ContainerAllocator>& v)
  {
    s << indent << "position_new: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position_new);
    s << indent << "reward: ";
    Printer<double>::stream(s, indent + "  ", v.reward);
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_MESSAGE_CURRENTRESPONSE_H
