// Generated by gencpp from file epos2/PositionResponse.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_POSITIONRESPONSE_H
#define EPOS2_MESSAGE_POSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2
{
template <class ContainerAllocator>
struct PositionResponse_
{
  typedef PositionResponse_<ContainerAllocator> Type;

  PositionResponse_()
    : position_new(0.0)
    , velocity(0.0)  {
    }
  PositionResponse_(const ContainerAllocator& _alloc)
    : position_new(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _position_new_type;
  _position_new_type position_new;

   typedef double _velocity_type;
  _velocity_type velocity;




  typedef boost::shared_ptr< ::epos2::PositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2::PositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionResponse_

typedef ::epos2::PositionResponse_<std::allocator<void> > PositionResponse;

typedef boost::shared_ptr< ::epos2::PositionResponse > PositionResponsePtr;
typedef boost::shared_ptr< ::epos2::PositionResponse const> PositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2::PositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2::PositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2::PositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2::PositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::PositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::PositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::PositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::PositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "338f3836bf85534ae0d5a5c9fd460d50";
  }

  static const char* value(const ::epos2::PositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x338f3836bf85534aULL;
  static const uint64_t static_value2 = 0xe0d5a5c9fd460d50ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2/PositionResponse";
  }

  static const char* value(const ::epos2::PositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2::PositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position_new\n\
float64 velocity\n\
";
  }

  static const char* value(const ::epos2::PositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2::PositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_new);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2::PositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2::PositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position_new: ";
    Printer<double>::stream(s, indent + "  ", v.position_new);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_MESSAGE_POSITIONRESPONSE_H
