// Generated by gencpp from file epos2/PositionRequest.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_POSITIONREQUEST_H
#define EPOS2_MESSAGE_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2
{
template <class ContainerAllocator>
struct PositionRequest_
{
  typedef PositionRequest_<ContainerAllocator> Type;

  PositionRequest_()
    : position(0.0)
    , isAbsolute(0)  {
    }
  PositionRequest_(const ContainerAllocator& _alloc)
    : position(0.0)
    , isAbsolute(0)  {
  (void)_alloc;
    }



   typedef double _position_type;
  _position_type position;

   typedef int32_t _isAbsolute_type;
  _isAbsolute_type isAbsolute;




  typedef boost::shared_ptr< ::epos2::PositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2::PositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionRequest_

typedef ::epos2::PositionRequest_<std::allocator<void> > PositionRequest;

typedef boost::shared_ptr< ::epos2::PositionRequest > PositionRequestPtr;
typedef boost::shared_ptr< ::epos2::PositionRequest const> PositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2::PositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2::PositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::PositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::PositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::PositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::PositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d897137170e76f0fd0be2a41e0b47515";
  }

  static const char* value(const ::epos2::PositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd897137170e76f0fULL;
  static const uint64_t static_value2 = 0xd0be2a41e0b47515ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2/PositionRequest";
  }

  static const char* value(const ::epos2::PositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2::PositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position\n\
int32 isAbsolute\n\
";
  }

  static const char* value(const ::epos2::PositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2::PositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.isAbsolute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2::PositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2::PositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "isAbsolute: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isAbsolute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_MESSAGE_POSITIONREQUEST_H
