// Generated by gencpp from file epos2/Position.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_POSITION_H
#define EPOS2_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <epos2/PositionRequest.h>
#include <epos2/PositionResponse.h>


namespace epos2
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace epos2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::epos2::Position > {
  static const char* value()
  {
    return "68c7b6e38e85a1444543be336041eac4";
  }

  static const char* value(const ::epos2::Position&) { return value(); }
};

template<>
struct DataType< ::epos2::Position > {
  static const char* value()
  {
    return "epos2/Position";
  }

  static const char* value(const ::epos2::Position&) { return value(); }
};


// service_traits::MD5Sum< ::epos2::PositionRequest> should match 
// service_traits::MD5Sum< ::epos2::Position > 
template<>
struct MD5Sum< ::epos2::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::epos2::Position >::value();
  }
  static const char* value(const ::epos2::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos2::PositionRequest> should match 
// service_traits::DataType< ::epos2::Position > 
template<>
struct DataType< ::epos2::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::epos2::Position >::value();
  }
  static const char* value(const ::epos2::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::epos2::PositionResponse> should match 
// service_traits::MD5Sum< ::epos2::Position > 
template<>
struct MD5Sum< ::epos2::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::epos2::Position >::value();
  }
  static const char* value(const ::epos2::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::epos2::PositionResponse> should match 
// service_traits::DataType< ::epos2::Position > 
template<>
struct DataType< ::epos2::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::epos2::Position >::value();
  }
  static const char* value(const ::epos2::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EPOS2_MESSAGE_POSITION_H
