// Generated by gencpp from file epos2/TorqueResponse.msg
// DO NOT EDIT!


#ifndef EPOS2_MESSAGE_TORQUERESPONSE_H
#define EPOS2_MESSAGE_TORQUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epos2
{
template <class ContainerAllocator>
struct TorqueResponse_
{
  typedef TorqueResponse_<ContainerAllocator> Type;

  TorqueResponse_()
    : state_new()
    , reward(0.0)
    , done(false)
    , velocity(0.0)
    , position_new(0.0)
    , current(0.0)  {
      state_new.assign(0.0);
  }
  TorqueResponse_(const ContainerAllocator& _alloc)
    : state_new()
    , reward(0.0)
    , done(false)
    , velocity(0.0)
    , position_new(0.0)
    , current(0.0)  {
  (void)_alloc;
      state_new.assign(0.0);
  }



   typedef boost::array<double, 3>  _state_new_type;
  _state_new_type state_new;

   typedef double _reward_type;
  _reward_type reward;

   typedef uint8_t _done_type;
  _done_type done;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _position_new_type;
  _position_new_type position_new;

   typedef double _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::epos2::TorqueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epos2::TorqueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TorqueResponse_

typedef ::epos2::TorqueResponse_<std::allocator<void> > TorqueResponse;

typedef boost::shared_ptr< ::epos2::TorqueResponse > TorqueResponsePtr;
typedef boost::shared_ptr< ::epos2::TorqueResponse const> TorqueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epos2::TorqueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epos2::TorqueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace epos2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::epos2::TorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epos2::TorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::TorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epos2::TorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::TorqueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epos2::TorqueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epos2::TorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8718dd5d2b7096e10fababe2ce8b9b84";
  }

  static const char* value(const ::epos2::TorqueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8718dd5d2b7096e1ULL;
  static const uint64_t static_value2 = 0x0fababe2ce8b9b84ULL;
};

template<class ContainerAllocator>
struct DataType< ::epos2::TorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epos2/TorqueResponse";
  }

  static const char* value(const ::epos2::TorqueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epos2::TorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] state_new\n\
float64 reward\n\
bool done\n\
float64 velocity\n\
float64 position_new\n\
float64 current\n\
\n\
";
  }

  static const char* value(const ::epos2::TorqueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epos2::TorqueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_new);
      stream.next(m.reward);
      stream.next(m.done);
      stream.next(m.velocity);
      stream.next(m.position_new);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TorqueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epos2::TorqueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epos2::TorqueResponse_<ContainerAllocator>& v)
  {
    s << indent << "state_new[]" << std::endl;
    for (size_t i = 0; i < v.state_new.size(); ++i)
    {
      s << indent << "  state_new[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state_new[i]);
    }
    s << indent << "reward: ";
    Printer<double>::stream(s, indent + "  ", v.reward);
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "position_new: ";
    Printer<double>::stream(s, indent + "  ", v.position_new);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPOS2_MESSAGE_TORQUERESPONSE_H
